### ISSUE TITLE
java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder

### ISSUE THREAD

**Issue by GreenL1nk** [WesJD/AnvilGUI#115]
```
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2186) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder
	at legotools.greenlink.ToolInv.openSetName(ToolInv.java:43) ~[?:?]
	at legotools.greenlink.LTMain.onInInvClick(LTMain.java:142) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	... 18 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at legotools.greenlink.ToolInv.openSetName(ToolInv.java:43) ~[?:?]
	at legotools.greenlink.LTMain.onInInvClick(LTMain.java:142) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	... 18 more
```

how fix that?

**Comment by portlek** [comment]
Could you show your pom.xml file?

**Comment by GreenL1nk** [comment]
repositories {
    mavenCentral()
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
}




dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.16.3-R0.1-SNAPSHOT'
    implementation 'com.github.WesJD.AnvilGUI:anvilgui:master-SNAPSHOT'
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        filter ReplaceTokens, tokens: [version: version]
    }
}


compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}``

**Comment by portlek** [comment]
try to use the shadowJar plugin for Gradle.

**Comment by GreenL1nk** [comment]
no, it's the same error anyway

**Comment by portlek** [comment]
you don't put your implementation into the jar, the shadowJar plugin allows you to do this. 
![image](https://user-images.githubusercontent.com/12835420/94369116-8a74e600-00f0-11eb-9c4d-9a2fefa0f03c.png)
add this shadow plugin into the plugins section and then 
![image](https://user-images.githubusercontent.com/12835420/94369125-99f42f00-00f0-11eb-8741-d6a056741847.png)
add some configuration for your plugin.
the relocation stuff is for me you don't have to use it.

**Comment by GreenL1nk** [comment]
> you don't put your implementation into the jar, the shadowJar plugin allows you to do this.
> ![image](https://user-images.githubusercontent.com/12835420/94369116-8a74e600-00f0-11eb-9c4d-9a2fefa0f03c.png)
> add this shadow plugin into the plugins section and then
> ![image](https://user-images.githubusercontent.com/12835420/94369125-99f42f00-00f0-11eb-8741-d6a056741847.png)
> add some configuration for your plugin.
> the relocation stuff is for me you don't have to use it.

thanks
