### ISSUE TITLE
Your server version isn't supported in AnvilGUI!

### ISSUE THREAD

**Issue by MegaNoam** [WesJD/AnvilGUI#125]
Greetings,
I recently encountered an error trying to use your API
I use Paper's Fork called Tuinity [[LINK]](https://github.com/Spottedleaf/Tuinity)

Is it possible to get an API to support it? At the end of the day the system I use is Spigot's Fork
Thanks in advance 💜

```
[17:18:57 ERROR]: Could not pass event InventoryClickEvent to MyPlugin v1.0
java.lang.ExceptionInInitializerError: null
        at com.modules.nickname.sql.NickEvents.OnClickInventory(NickEvents.java:64) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor125.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2528) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1322) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
        at net.wesjd.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:49) ~[?:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_241]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:49) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
        ... 21 more
```

**Comment by WesJD** [comment]
Update your dependency using the dependency information in the README. Your server version already is supported.
