### ISSUE TITLE
Issue with library java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder

### ISSUE THREAD

**Issue by celciusjj** [WesJD/AnvilGUI#133]
Hi, i have this issue when i make the anvil GUI in my console, can you help me please. thank you

`java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder
	at com.celcius.handlers.TransactionsAnvil.depositMoney(TransactionsAnvil.java:41) ~[?:?]
	at com.celcius.menus.MainMenu.onClick(MainMenu.java:57) ~[?:?]
	at com.celcius.utils.GuiManager.onClick(GuiManager.java:37) ~[?:?]
	at com.celcius.events.GuiEvent.onClick(GuiEvent.java:32) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor6.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-553]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-553]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-553]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2542) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008) ~[patched_1.16.5.jar:git-Paper-553]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-553]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-553]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-553]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	... 24 more`
	
	My code is the same of the example...
	
	`public void depositMoney(Player p) {
        new AnvilGUI.Builder()
                .onClose(player -> {                                        //called when the inventory is closing
                    player.sendMessage("You closed the inventory.");
                })
                .onComplete((player, text) -> {                             //called when the inventory output slot is clicked
                    if(text.equalsIgnoreCase("you")) {
                        player.sendMessage("You have magical powers!");
                        return AnvilGUI.Response.close();
                    } else {
                        return AnvilGUI.Response.text("Incorrect.");
                    }
                })
                .preventClose()                                             //prevents the inventory from being closed
                .text("What is the meaning of life?")                       //sets the text the GUI should start with
                .itemLeft(new ItemStack(Material.IRON_SWORD))               //use a custom item for the first slot
                .itemRight(new ItemStack(Material.IRON_INGOT))              //use a custom item for the second slot
                .onLeftInputClick(player -> player.sendMessage("sword"))    //called when the left input slot is clicked
                .onRightInputClick(player -> player.sendMessage("ingot"))   //called when the right input slot is clicked
                .title("Enter your answer.")                                //set the title of the GUI (only works in 1.14+)
                .plugin(plugin)                                   //set the plugin instance
                .open(p);
    }`

**Comment by portlek** [comment]
could you paste your pom.xml/gradle file?

**Comment by celciusjj** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>celcius</groupId>
    <artifactId>PersonalBank</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>mojang</id>
            <name>Mojang's Repository</name>
            <url>https://libraries.minecraft.net/</url>
        </repository>
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/repository/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
        <repository>
            <id>papermc</id>
            <url>https://papermc.io/repo/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.destroystokyo.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.16.5-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>authlib</artifactId>
            <version>1.5.21</version>
        </dependency>

        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>4.6.0</version>
        </dependency>

        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.5.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>`

this is the pom.xml

**Comment by celciusjj** [comment]
can you show me one example?

**Comment by celciusjj** [comment]
Thank you, now is working!
