### ISSUE TITLE
[Help Wanted] I keep getting errors trying to make an anvil gui.

### ISSUE THREAD

**Issue by MangoSwirl** [WesJD/AnvilGUI#134]
I think it's a problem with the plugin instance, but I'm not sure why it would be. I'm using the example, so it must be a problem with the arguments I'm giving it. I'm supplying the plugin instance as a `Plugin` class. That is what I'm supposed to do, right? My IDE's validation seems to think it should work; it's not until I test it out that I get the errors. What could be the problem?

Edit: Now I tried supplying it as a `JavaPlugin` class.
Edit 2: I switched back to `Plugin` after looking at the Javadocs.

**Comment by portlek** [comment]
What was the error you get?

**Comment by MangoSwirl** [comment]
The errors vary. This is the latest one I got.
```
[07:30:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'entername' in plugin RealName v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-582]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-582]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-582]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-582]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder
        at com.hillcraft.realname.commands.PluginCommands.onCommand(PluginCommands.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-582]
        ... 19 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-582]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-582]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at com.hillcraft.realname.commands.PluginCommands.onCommand(PluginCommands.java:44) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-582]
        ... 19 more
```
This is my code:
```java
Player player = (Player) commandSender;
JavaPlugin instance = JavaPlugin.getProvidingPlugin(this.getClass());

new AnvilGUI.Builder()
                    .onClose(ply -> {
                        ply.sendMessage("You closed the inventory.");
                    })
                    .onComplete((ply, text) -> {
                        if(text.equalsIgnoreCase("you")) {
                            ply.sendMessage("You have magical powers!");
                            return AnvilGUI.Response.close();
                        } else {
                            return AnvilGUI.Response.text("Incorrect.");
                        }
                    })
                    .preventClose()
                    .text("What is the meaning of life?")
                    .itemLeft(new ItemStack(Material.IRON_SWORD))
                    .itemRight(new ItemStack(Material.IRON_INGOT))
                    .onLeftInputClick(ply -> ply.sendMessage("sword"))
                    .onRightInputClick(ply -> ply.sendMessage("ingot"))
                    .title("Enter your answer.")
                    .plugin(instance)
                    .open(player);
```

**Comment by portlek** [comment]
use maven-shade-plugin to put the library into your jar file.

**Comment by MangoSwirl** [comment]
I think I did. I put all the code from the README into my pom.xml and I used a plugin that comes with my IDE to automatically download and bundle it with my jar.

**Comment by portlek** [comment]
is the jar file has the anvil gui library?

**Comment by portlek** [comment]
what is the error now?

**Comment by MangoSwirl** [comment]
Same as before.

**Comment by portlek** [comment]
how you compile your project? you should use mvn clean package command

**Comment by MangoSwirl** [comment]
Ok, I'll try that.

**Comment by portlek** [comment]
also, can you share your pom file, probably the issue in it.

**Comment by portlek** [comment]
i can recommend you to use my parent pom projects here is the usage in your case;
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.portlek</groupId>
    <artifactId>ppom</artifactId>
    <version>2.5.3</version>
  </parent>
  <groupId>groupId</groupId>
  <artifactId>RealName</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>RealName</name>
  <description>Custom plugin for HillCraft.</description>
  <properties>
    <mainClass>com.hillcraft.realname.Main</mainClass>
    <java.version>14</java.version>
  </properties>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>plugin.yml</include>
        </includes>
      </resource>
    </resources>
  </build>
  <repositories>
    <repository>
      <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
      <id>spigot-repo</id>
    </repository>
    <repository>
      <url>https://repo.codemc.io/repository/maven-snapshots/</url>
      <id>codemc-snapshots</id>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>org.spigotmc</groupId>
      <artifactId>spigot-api</artifactId>
      <version>1.16.5-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>net.wesjd</groupId>
      <artifactId>anvilgui</artifactId>
      <version>1.5.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
</project>

```

**Comment by portlek** [comment]
just type mvn clean package again. then it will work.

**Comment by MangoSwirl** [comment]
Ok. Let me try that.
