### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Wolfeiiii** [WesJD/AnvilGUI#136]
`org.bukkit.command.CommandException: Unhandled exception executing command 'openmulte' in plugin WarvilleMulte v1.0-SNAPSHOT

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:762) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1935) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1778) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1731) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1037) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder

at me.wolfeiii.warvillemulte.gui.OpenMulteInventory.<init>(OpenMulteInventory.java:20) ~[?:?]

at me.wolfeiii.warvillemulte.commands.MultaCommand.onCommand(MultaCommand.java:35) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

... 19 more

Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder

at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]

at me.wolfeiii.warvillemulte.gui.OpenMulteInventory.<init>(OpenMulteInventory.java:20) ~[?:?]

at me.wolfeiii.warvillemulte.commands.MultaCommand.onCommand(MultaCommand.java:35) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:3068-Spigot-bd6b566-59e2ce9]

... 19 more`

This is my pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.wolfeiii</groupId>
    <artifactId>WarvilleMulte</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>WarvilleMulte</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <defaultGoal>clean package</defaultGoal>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>plugin.yml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>

    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.15.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.milkbowl</groupId>
            <artifactId>vaultapi</artifactId>
            <version>1.7</version>
        </dependency>
        <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
            <version>7.9.1.1</version>
        </dependency>
        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.5.0-SNAPSHOT</version>
         </dependency>
    </dependencies>

</project>
`

**Comment by WesJD** [comment]
You have not provided the correct scope for the dependency. This repo is not a support area for the maven shade plugin.
