### ISSUE TITLE
error when i try and open anvilgui

### ISSUE THREAD

**Issue by Endercass** [WesJD/AnvilGUI#138]
Whenever I try to enter the anvil gui i get this error in console:
`org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[TestingServer.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[TestingServer.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1893) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [TestingServer.jar:git-Spigot-79a30d7-acbc348]
at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder
at tk.skydirt.core.UI.CustomItemUI.clicked(CustomItemUI.java:73) ~[?:?]
at tk.skydirt.core.listeners.InventoryClickListener.onClick(InventoryClickListener.java:31) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[TestingServer.jar:git-Spigot-79a30d7-acbc348]
... 15 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder
at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[TestingServer.jar:git-Spigot-79a30d7-acbc348]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[TestingServer.jar:git-Spigot-79a30d7-acbc348]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at tk.skydirt.core.UI.CustomItemUI.clicked(CustomItemUI.java:73) ~[?:?]
at tk.skydirt.core.listeners.InventoryClickListener.onClick(InventoryClickListener.java:31) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[TestingServer.jar:git-Spigot-79a30d7-acbc348]
... 15 more`

**Comment by Endercass** [comment]
I forgot, heres my code for the class that contains the menu. https://pastebin.com/EAwA8drm

**Comment by portlek** [comment]
looks like you didn't shade the library into your jar.

**Comment by Endercass** [comment]
> 
> 
> looks like you didn't shade the library into your jar.
So uhhh.. what does that mean? (I am brand new to using maven)
