### ISSUE TITLE
NoClassDefFoundError on creating an AnvilGUI (ListenUp)

### ISSUE THREAD

**Issue by TheClowner** [WesJD/AnvilGUI#147]
I've updated my plugin to use AnvilGUI 1.5.1-SNAPSHOT and now I'm getting this error whenever I try to build an AnvilGUI.

```
[08:51:26] [Server thread/WARN]: [ccShop] Task #28 for ccShop v1.2.0 generated an exception
java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$ListenUp
	at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:90) ~[?:?]
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
	at net.clownercraft.ccshop.gui.PlayerShopManagerGUI.openPriceGUI(PlayerShopManagerGUI.java:870) ~[?:?]
	at net.clownercraft.ccshop.gui.GuiManager.openInventory(GuiManager.java:92) ~[?:?]
	at net.clownercraft.ccshop.gui.PlayerShopManagerGUI.lambda$handleItemManagerGuiClick$21(PlayerShopManagerGUI.java:1509) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$ListenUp
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 13 more
```

Here's the code that's opening the GUI:
```java
    public InventoryView openPriceGUI(Player player, ShopItem item, boolean sell){
        double currPrice = (sell)? item.getSellPrice():item.getBuyPrice();

        String title = lang.getGuiMessage(player, "Gui.Title.PlayerManager.price")
                .replaceAll("\\{price}",Utils.formatDouble(currPrice,2));

        new AnvilGUI.Builder()
            .onClose((player1 -> {}))
            .onComplete((p,t) -> AnvilGUI.Response.close())
            .itemLeft(item.getSample())
            .text(Utils.formatDouble(currPrice,2))
            .title(title)
            .plugin(ccShopPlugin.getInstance())
            .open(player);

        return player.getOpenInventory();
    }
```
    
It's not throwing an error on the Builder class so I believe it is being shaded into the jar correctly, it just has some issue with the Listener class.

**Comment by tchristofferson** [comment]
I had an issue with the maven shade plugin not being able to shade the AnvilGUI because it doesn't work with Java 16. Make sure you have Java 16 and are using it. If it still doesn't work try using maven shade plugin version 3.3.0-SNAPSHOT (you might have to add the snapshot repository in your pom)

**Comment by TheClowner** [comment]
Yup, updating maven shade plugin to 3.3.0-SNAPSHOT has resolved my issue.
