### ISSUE TITLE
An error occurred on Paper 1.13.2

### ISSUE THREAD

**Issue by BingYanchi** [WesJD/AnvilGUI#165]
I'm not sure if it is my cause. If yes, please tell me how to do it. I don't know why there are 1.17.1 errors on Paper 1.13.2.

I used the shade of 3.3.0-SNAPSHOT, and the plug-in itself is java 8.
```
[20:09:56 ERROR]: Fatal error trying to convert PartySystem v0.3:cn/yistars/party/bukkit/anvilgui/version/Wrapper1_17_R1.class
>java.lang.IllegalArgumentException: Unsupported class file major version 60
at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195) ~[patched_1.13.2.jar:git-Paper-655]
at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176) ~[patched_1.13.2.jar:git-Paper-655]
at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.util.Commodore.convert(Commodore.java:170) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:238) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:113) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-655]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
at cn.yistars.party.bukkit.anvilgui.version.VersionMatcher.<init>(VersionMatcher.java:23) ~[?:?]
at cn.yistars.party.bukkit.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
at cn.yistars.party.bukkit.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
at cn.yistars.party.bukkit.gui.Anvil.CreateAnvil(Anvil.java:29) ~[?:?]
at cn.yistars.party.bukkit.command.PartyCommand.onCommand(PartyCommand.java:33) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-655]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[20:09:56 ERROR]: null
>org.bukkit.command.CommandException: Unhandled exception executing command 'partysystem:party' in plugin PartySystem v0.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-655]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
>Caused by: java.lang.UnsupportedClassVersionError: cn/yistars/party/bukkit/anvilgui/version/Wrapper1_17_R1 has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-655]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
at cn.yistars.party.bukkit.anvilgui.version.VersionMatcher.<init>(VersionMatcher.java:23) ~[?:?]
at cn.yistars.party.bukkit.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
at cn.yistars.party.bukkit.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
at cn.yistars.party.bukkit.gui.Anvil.CreateAnvil(Anvil.java:29) ~[?:?]
at cn.yistars.party.bukkit.command.PartyCommand.onCommand(PartyCommand.java:33) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-655]
... 15 more
```

**Comment by BingYanchi** [comment]
package cn.yistars.party.bukkit.gui;

import cn.yistars.party.bukkit.BungeeChannelManager;
import cn.yistars.party.bukkit.Party;
import net.wesjd.anvilgui.AnvilGUI;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

public class Anvil {
    public static void CreateAnvil(Player player, String command, String title, String text) {
        new AnvilGUI.Builder()
                .onComplete((p, playerText) -> {
                    if (playerText.equals(text)) return AnvilGUI.Response.text(text);
                    switch (command) {
                        case "invite": case "kick":
                            String Command = "party " + command + " " + playerText;
                            BungeeChannelManager.sendPluginMessage(p, "PlayerCommand", Command);
                            break;
                        case "search":
                            break;
                    }
                    return AnvilGUI.Response.close();
                })
                .text(text)
                .itemLeft(new ItemStack(Material.PAPER))
                .title(title)
                .plugin(Party.instance)
                .open(player);
    }
}

**Comment by thenilsdev** [comment]
#164 fixes this
