### ISSUE TITLE
 Error in console (NoSuchMethodError)

### ISSUE THREAD

**Issue by ImFound** [WesJD/AnvilGUI#177]
[11:59:34 ERROR]: Could not pass event InventoryClickEvent to AwareVehicles v1.0-SNAPSHOT
java.lang.NoSuchMethodError: 'org.bukkit.inventory.Inventory net.wesjd.anvilgui.AnvilGUI$Response.getInventoryToOpen()'
        at net.wesjd.anvilgui.AnvilGUI$ListenUp.onInventoryClick(AnvilGUI.java:259) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Purpur-606]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Purpur-606]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Purpur-606]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2420) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1186) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1179) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1155) ~[patched_1.15.2.jar:git-Purpur-606]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:998) ~[patched_1.15.2.jar:git-Purpur-606]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by WesJD** [comment]
Use `mvn clean package` on your plugin, looks like you are compiling old code at some point in the process.
