### ISSUE TITLE
Add "minimizeJar"=false note to provided pom.xml

### ISSUE THREAD

**Issue by Qrashi** [WesJD/AnvilGUI#190]
I get the following error:
`java.lang.NoClassDefFoundError: Could not initialize class link.ignyte.plugins.bedwars.anvilgui.AnvilGUI` 

I am relocating anvilGUI into my plugin using this maven-shade-plugin configuration:
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.3.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>net.wesjd.anvilgui</pattern>
                                    <shadedPattern>link.ignyte.plugins.bedwars.anvilgui</shadedPattern>
                                </relocation>                                
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
(There is a bit more configuration, but I chose only to share the "important" bits)

Also in my built jar, there IS an anvilGUI class file so it must be some kind of class loading error. Right?

Please help :)

**Comment by Sytm** [comment]
Could you paste the full class not found error

**Comment by Qrashi** [comment]
Here you go:
```
java.lang.NoClassDefFoundError: Could not initialize class link.ignyte.plugins.bedwars.anvilgui.AnvilGUI
        at link.ignyte.plugins.bedwars.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[BedWars.jar:?]
        at link.ignyte.plugins.bedwars.Inventories.Setup.SetupManager$3.run(SetupManager.java:246) ~[BedWars.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-137]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-137]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-137]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-137] 
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-137]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-137]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-137]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by Sytm** [comment]
Do a `mvn clean` and then try again perhaps. Because it is kinda wierd that the inner class cant initialize the outer class.

**Comment by Qrashi** [comment]
Okay, I have done `mvn clean package`  and now I got another error message: `AnvilGUI does not support server version 1.18.1-R0.1`
It seems as if ALL the version wrappers for anvilGUI are missing in the final jar...

**Comment by Sytm** [comment]
I guess you are already using the CodeMC repository. What GroupId:ArtifactID:Version of Anvil GUI are you using?

**Comment by Qrashi** [comment]
1.5.3-SNAPSHOT, but it seems that there are no versionWrappers in the shaded jar...

**Comment by Qrashi** [comment]
I'm just using the maven config provided in the README.md

**Comment by Sytm** [comment]
Try adding
```xml
<configuration>
    <minimizeJar>false</minimizeJar>
</configuration>
```
to the configuration of the maven shade plugin

**Comment by Qrashi** [comment]
Thanks, that solved my problem.

Maybe you could add this to the example pom.xml provided because a lot of tutorials tell one to set "minimizeJar" to true.

**Comment by Qrashi** [comment]
Should I create a new issue?

**Comment by Sytm** [comment]
Rather not. At the moment all the information is in one place

**Comment by Qrashi** [comment]
No I think you misunderstood, I meant to add a warning to the README.md not to the actual pom.xml

**Comment by Sytm** [comment]
Ahhh, just create a pull-request with the change to the README yourself

**Comment by Qrashi** [comment]
I just created a pull request :)
