### ISSUE TITLE
Error using CraftBukkit remapped

### ISSUE THREAD

**Issue by GavinGoGaming** [WesJD/AnvilGUI#201]
Could not pass event InventoryClickEvent to KlashWorld v1.0
java.lang.NoSuchFieldError: inventoryMenu
        at net.wesjd.anvilgui.version.Wrapper1_18_R2.setActiveContainerDefault(Wrapper1_18_R2.java:59) ~[KWItems.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:175) ~[KWItems.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:167) ~[KWItems.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:133) ~[KWItems.jar:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:493) ~[KWItems.jar:?]
        
Something with using remapped. Im using the 1.5.3-SNAPSHOT on 1.18.2 precompiled jar (from [here](https://repo.codemc.io/#browse/browse:maven-snapshots:net%2Fwesjd%2Fanvilgui%2F1.5.3-SNAPSHOT%2F1.5.3-20220302.153253-5))

**Comment by GavinGoGaming** [comment]
_b u m p_

**Comment by GavinGoGaming** [comment]
any1 know whats goin on?
