### ISSUE TITLE
Unsupported class file major version 61

### ISSUE THREAD

**Issue by MBDOFF** [WesJD/AnvilGUI#203]
![image](https://user-images.githubusercontent.com/62158577/161439071-5b07fea4-5559-46af-82ae-14a741eac3af.png)

I saw #193, but  I am using gradle.

**Comment by Sytm** [comment]
What is the JDK version gradle runs on? It should be shown when you run `./gradlew -v` or `gradle -v`.

That must be atleast Java version 17.

Also make sure you are using the latest version of Gradle (7.4.2) and ShadowJar (7.1.2) itself.

**Comment by MBDOFF** [comment]
I fixed it, but now I have another problem.

> `04.04 12:52:30 [Server] ERROR Could not pass event InventoryClickEvent to ----v22.04.04
> 04.04 12:52:30 [Server] INFO java.lang.ExceptionInInitializerError: null
> 04.04 12:52:30 [Server] INFO at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[-----22.04.04.jar:?]
> 04.04 12:52:30 [Server] INFO at one.mbd.----.gui.admin.PlayersGUI.onInventoryClick(PlayersGUI.java:106) ~[-----22.04.04.jar:?]
> 04.04 12:52:30 [Server] INFO at one.mbd.----.listeners.InventoryClickListener.onInventoryClick(InventoryClickListener.java:21) ~[-----22.04.04.jar:?]
> 04.04 12:52:30 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor618.execute(Unknown Source) ~[?:?]
> 04.04 12:52:30 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:30 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:30 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:30 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2807) ~[app:?]
> 04.04 12:52:30 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
> 04.04 12:52:30 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
> 04.04 12:52:30 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
> 04.04 12:52:30 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:30 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
> 04.04 12:52:30 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
> 04.04 12:52:30 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
> 04.04 12:52:32 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
> 04.04 12:52:32 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
> 04.04 12:52:32 [Server] INFO Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_17_R1"
> 04.04 12:52:32 [Server] INFO at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:26) ~[-----22.04.04.jar:?]
> 04.04 12:52:32 [Server] INFO at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[-----22.04.04.jar:?]
> 04.04 12:52:32 [Server] INFO ... 25 more
> 04.04 12:52:32 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.Wrapper1_17_R1
> 04.04 12:52:32 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-409]
> 04.04 12:52:32 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
> 04.04 12:52:32 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
> 04.04 12:52:32 [Server] INFO at java.lang.Class.forName(Class.java:375) ~[?:?]
> 04.04 12:52:32 [Server] INFO at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:22) ~[-----22.04.04.jar:?]
> 04.04 12:52:32 [Server] INFO at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[-----22.04.04.jar:?]
> 04.04 12:52:32 [Server] INFO ... 25 more
