### ISSUE TITLE
ERROR: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/ContainerAnvil

### ISSUE THREAD

**Issue by calledzen** [WesJD/AnvilGUI#211]
Hi,
We have a server API on our network that runs with AnvilGUI and as soon as I use this API on my local network, I get this error. My network is running SimpleCloud on version 1.16.5 using a Paper 1.16.5.

On the main network everything is without problems, so I ask where the error comes from.

By the way, I use Java 17 because the Cloud and the ServerAPI are written on it.

```
[Lobby-1][15:02:43 ERROR]: Error occurred while enabling NytouServerApi v1.0 (Is it up to date?)
[Lobby-1]java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/ContainerAnvil
[Lobby-1]ud >   at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
[Lobby-1]ud >   at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
[Lobby-1]ud >   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
[Lobby-1]ud >   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
[Lobby-1]ud >   at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at java.lang.ClassLoader.loadClass(ClassLoader.java:574) ~[?:?]
[Lobby-1]ud >   at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872) ~[?:?]
[Lobby-1]ud >   at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Lobby-1]ud >   at io.nytou.modules.plugin.loader.PluginLoadingHandler.enablePlugin(PluginLoadingHandler.java:46) ~[?:?]
[Lobby-1]ud >   at io.nytou.modules.plugin.NytouPlugin.loadModules(NytouPlugin.java:194) ~[?:?]
[Lobby-1]ud >   at io.nytou.modules.plugin.NytouPlugin.onEnable(NytouPlugin.java:126) ~[?:?]
[Lobby-1]ud >   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:519) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:433) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:304) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at java.lang.Thread.run(Thread.java:833) [?:?]
[Lobby-1]Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.ContainerAnvil
[Lobby-1]ud >   at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[server.jar:git-Paper-6556d50]
[Lobby-1]ud >   at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Lobby-1]ud >   ... 23 more

```

MAVEN IMPORTS:
```
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>

        <dependency>
            <groupId>net.wesjd</groupId>
            <artifactId>anvilgui</artifactId>
            <version>1.5.3-SNAPSHOT</version>
        </dependency>
```

**Comment by joestr** [comment]
Did you forgot to shade in the AnvilGUI dependency?

**Comment by calledzen** [comment]
I had the wrong java version defined in my maven config

**Comment by DereWah** [comment]
How did you fix this? I'm compiling my plugin with java 1.8 and spigot 1.13.3_R0.1-Snapshot and running it on a paper 1.19.2 server
