### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by iXanadu13** [WesJD/AnvilGUI#213]
Thank you for your previous respond! @Sytm 
But I have another problem that must I name the final class "anvilgui"?
Or "anvilgui" can be the normal class in my plugin?
Actually what I chose is the second one now...

**Comment by Sytm** [comment]
Did you mean this?
```xml
<relocation>
    <pattern>net.wesjd.anvilgui</pattern>
    <shadedPattern>xanadu.namecard.commands.anvilgui</shadedPattern>
</relocation>
```

**Comment by iXanadu13** [comment]
Yes,it is.
Actually the final class of my plugin is in package xanadu.namecard.

**Comment by Sytm** [comment]
These relocations move the classes themselves from one package (`pattern`) to another (`shadedPattern`).

So for example the class `net.wesjd.anvilgui.AnvilGUI` gets moved to `xanadu.namecard.commands.anvilgui.AnvilGUI`. But this moving is only important when the plugin is on server.

While programming everything is still at `net.wesjd.anvilgui.AnvilGUI`.

And and I think you maybe should remove the `commands`.

```xml
<relocation>
    <pattern>net.wesjd.anvilgui</pattern>
    <shadedPattern>xanadu.namecard.anvilgui</shadedPattern>
</relocation>
```
But you must keep the `anvilgui` at the end of both

**Comment by iXanadu13** [comment]
Here is the pictrue of my plugin's structure.
![image](https://user-images.githubusercontent.com/104714710/166142074-8868c26f-3e51-4cf1-ae82-038c8b899e1b.png)

**Comment by iXanadu13** [comment]
The same error is still there...
```
Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder
        at xanadu.namecard.commands.anvilgui.onCommand(anvilgui.java:21) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-788]
        ... 19 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[server.jar:git-Paper-788]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[server.jar:git-Paper-788]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at xanadu.namecard.commands.anvilgui.onCommand(anvilgui.java:21) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-788]
        ... 19 more
```
I have changed the pom.xml as what you advised me to.

**Comment by iXanadu13** [comment]
> 

I have do that as what I wrote in the previous two comments.
But it still doesn't work.

**Comment by iXanadu13** [comment]
Here is my plugin's all files.When I perform the command "/towname" to open an anvil GUI,the error happens.
Can you point out where is the problem from.
[NameCard.zip](https://github.com/WesJD/AnvilGUI/files/8598925/NameCard.zip)

**Comment by iXanadu13** [comment]
![image](https://user-images.githubusercontent.com/104714710/166149544-8e33761c-5715-4822-8ae5-a7ccecd31056.png)

**Comment by joestr** [comment]
What jar-file from the `target` folder were you using? Because the shaded was properly built.  
  
![image](https://user-images.githubusercontent.com/20691668/166151246-7d6d2cf3-4026-46cf-9d27-e255814313e2.png)
_(The one highlighted by the red rectangle has AnvilGUI included.)_

**Comment by joestr** [comment]
Despite that, you should carefully read the instructions in the section about [how to use AnvilGUI in your plugin](https://github.com/WesJD/AnvilGUI#in-your-plugin).

In your `GUI`-class you have following line:
```
new AnvilGUI.Builder().title(title).open(p);
```

Which is incomplete.

Take a look at the [full example](https://github.com/WesJD/AnvilGUI#a-full-example-combining-all-methods) to get a feeling how AnvilGUI works as library.

**Comment by iXanadu13** [comment]
> What jar-file from the `target` folder were you using? Because the shaded one was properly built.
> 
> ![image](https://user-images.githubusercontent.com/20691668/166151246-7d6d2cf3-4026-46cf-9d27-e255814313e2.png) _(The one highlighted by the red rectangle has AnvilGUI included.)_

I use IDEA.

**Comment by iXanadu13** [comment]
> Despite that, you should carefully read the instructions in the section about [how to use AnvilGUI in your plugin](https://github.com/WesJD/AnvilGUI#in-your-plugin).
> 
> In your `GUI`-class you have following line:
> 
> ```
> new AnvilGUI.Builder().title(title).open(p);
> ```
> 
> Which is incomplete.
> 
> Take a look at the [full example](https://github.com/WesJD/AnvilGUI#a-full-example-combining-all-methods) to get a feeling how AnvilGUI works as library.

Sorry, I still can't find the flaw in my codes.I just want to open a gui which is empty and titled "Name Change"

**Comment by iXanadu13** [comment]
Thank you for your respond very much. @joestr 
However,now my biggest problem is still that `Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder` .
So I wonder if I can solve this problem by copying the AnvilGUI codes in my project.....
So what should I do to solve the problem?

**Comment by joestr** [comment]
If you build your plugin there is a `target` directory. There are two jar-files in it. THe frist one is `NameCard-1.0-SNAPSHOT.jar` and the second one is `original-NameCard-1.0-SNAPSHOT.jar`. Which one of those do you put on your Spigot/Paper server?

**Comment by iXanadu13** [comment]
> If you build your plugin there is a `target` directory. There are two jar-files in it. The frist one is `NameCard-1.0-SNAPSHOT.jar` and the second one is `original-NameCard-1.0-SNAPSHOT.jar`. Which one of those do you put on your Spigot/Paper server?

What?I never get two files.I can only get one jar-file at one time.

**Comment by joestr** [comment]
What's its name?

**Comment by iXanadu13** [comment]
What I got is this
[NameCard.zip](https://github.com/WesJD/AnvilGUI/files/8599253/NameCard.zip)
.

**Comment by iXanadu13** [comment]
I never change its name and that's its original appearance.

**Comment by joestr** [comment]
> What I got is this [NameCard.zip](https://github.com/WesJD/AnvilGUI/files/8599253/NameCard.zip) .

Yeah, and that's where the problem is. The .jar-file in the zip package **does not have** AnvilGUI in it.

**Comment by iXanadu13** [comment]
> > What I got is this [NameCard.zip](https://github.com/WesJD/AnvilGUI/files/8599253/NameCard.zip) .
> 
> Yeah, and that's where the problem is. The .jar-file in the zip package **does not have** AnvilGUI in it.

Yes,that's why i what to copy AnvilGUI code in it....
So what should i do to deal with it.

**Comment by iXanadu13** [comment]
Oh,I found something different.
![image](https://user-images.githubusercontent.com/104714710/166153960-2deb3561-1522-437a-a558-4c16a0197506.png)

**Comment by iXanadu13** [comment]
So which one should I use?

**Comment by joestr** [comment]
Run `mvn clean package` in IntelliJ (instructions are [here](https://www.jetbrains.com/help/idea/work-with-maven-goals.html#run_goal))

And then (in most cases) the larger file. In this case `NameCard-1.0-SNAPSHOT.jar`.

**Comment by iXanadu13** [comment]
Should i delete them all?
![image](https://user-images.githubusercontent.com/104714710/166154380-cf7eb730-146b-4d2a-949a-46a516ee2256.png)

**Comment by joestr** [comment]
Yes.

**Comment by iXanadu13** [comment]
But i can't found `mvn clean package`.
![image](https://user-images.githubusercontent.com/104714710/166154662-c30ce828-65ed-4c8e-96b1-2ed5124d5b8d.png)

**Comment by joestr** [comment]
Just write it out.

**Comment by iXanadu13** [comment]
It succeed! I won to get a comple jar-file.
But now the problem is that:
```
used by: java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[server.jar:git-Paper-788]
        at xanadu.namecard.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:488) ~[?:?]
        at xanadu.namecard.commands.AnvGUI.onCommand(AnvGUI.java:21) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-788]
        ... 19 more
```

**Comment by iXanadu13** [comment]
All error report:
```
[00:29:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'towname' in plugin NameCard v2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Paper-788]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[server.jar:git-Paper-788]
        at xanadu.namecard.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:488) ~[?:?]
        at xanadu.namecard.commands.AnvGUI.onCommand(AnvGUI.java:21) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-788]
        ... 19 more
```

**Comment by joestr** [comment]
> Despite that, you should carefully read the instructions in the section about [how to use AnvilGUI in your plugin](https://github.com/WesJD/AnvilGUI#in-your-plugin).
> 
> In your `GUI`-class you have following line:
> 
> ```
> new AnvilGUI.Builder().title(title).open(p);
> ```
> 
> Which is incomplete.
> 
> Take a look at the [full example](https://github.com/WesJD/AnvilGUI#a-full-example-combining-all-methods) to get a feeling how AnvilGUI works as library.

Use the full example.

**Comment by iXanadu13** [comment]
`   .plugin(myPluginInstance)                                          //set the plugin instance`
Can you explain what is plugin instance

**Comment by joestr** [comment]
Yes.

**Comment by iXanadu13** [comment]
```
[01:03:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'towname' in plugin NameCard v2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Paper-788]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[server.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.setDisplayName(String)" because "paperMeta" is null
        at xanadu.namecard.anvilgui.AnvilGUI.<init>(AnvilGUI.java:161) ~[?:?]
        at xanadu.namecard.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[?:?]
        at xanadu.namecard.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
        at xanadu.namecard.commands.AnvGUI.onCommand(AnvGUI.java:43) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-788]
        ... 19 more
```


But there is no such "paperMeta" in my plugin.


![image](https://user-images.githubusercontent.com/104714710/166156604-a34d6406-717b-41d3-8946-633cf124974f.png)

**Comment by joestr** [comment]
Sharing the affected code part would help.
