### ISSUE TITLE
AnvilGui doesn not support R1_1.19

### ISSUE THREAD

**Issue by ToberoCat** [WesJD/AnvilGUI#219]
So I'm using your api in my plugin for 1.19, bcause github said it's with 1.19 compatible.
I got this problem reported form one of my users. He is using purpur and is on 1.19

```java
ava.lang.ExceptionInInitializerError: null
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[ImprovedFactionsV1.4.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1670]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1670]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1670]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_19_R1"
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:26) ~[ImprovedFactionsV1.4.2.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[ImprovedFactionsV1.4.2.jar:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.Wrapper1_19_R1
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
```

I updated the maven repo & dependency and was using it on compile. It was working fine for me on 1.18, so probably just no 1.19 support yet

**Comment by portlek** [comment]
you can use [jitpack](https://jitpack.io/#WesJD/AnvilGUI/a8eca89117) until the repository updated.

**Comment by Sytm** [comment]
You don't need to use Jitpack, the repo is already updated to Minecraft 1.19 since [June 6th](https://repo.codemc.io/#browse/browse:maven-public:net%2Fwesjd%2Fanvilgui%2F1.5.3-SNAPSHOT%2F1.5.3-20220609.032626-7%2Fanvilgui-1.5.3-20220609.032626-7.jar). 

Before building your plugin try using `mvn clean` or if that doesn't work delete your local maven repository cache.
