### ISSUE TITLE
NoSuchMethodError on 1.19.2 when opening inventory

### ISSUE THREAD

**Issue by SnickoDeadMC** [WesJD/AnvilGUI#228]
Getting an error when trying to open an inventory on 1.19.2 (worked on previous versions):

`java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
        at net.wesjd.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:98) ~[DeadAPI.jar:?]
        at net.wesjd.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:91) ~[DeadAPI.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:176) ~[DeadAPI.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:164) ~[DeadAPI.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[DeadAPI.jar:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[DeadAPI.jar:?]`

Edit: for better formatting: https://pastebin.com/tB2rc96y

**Comment by SnickoDeadMC** [comment]
My bad, needed to update spigot in maven to 1.19.2-R0.1-SNAPSHOT
