### ISSUE TITLE
Server version not supported

### ISSUE THREAD

**Issue by MattyTomas** [WesJD/AnvilGUI#248]
My server version is 1.16.5 and it's present in the home page list but I receive this error:

`Caused by: java.lang.ExceptionInInitializerError
        at dev.mattytomas.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:558) ~[?:?]
        at dev.mattytomas.roleplaycore.AziendaDepartment.AziendaAdmin.Events.depositMoney(Events.java:234) ~[?:?]
        at dev.mattytomas.roleplaycore.AziendaDepartment.AziendaAdmin.Events.onInventoryClick(Events.java:404) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        ... 18 more
Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_16_R3"
        at dev.mattytomas.anvilgui.version.VersionMatcher.match(VersionMatcher.java:34) ~[?:?]
        at dev.mattytomas.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:39) ~[?:?]
        at dev.mattytomas.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:558) ~[?:?]
        at dev.mattytomas.roleplaycore.AziendaDepartment.AziendaAdmin.Events.depositMoney(Events.java:234) ~[?:?]
        at dev.mattytomas.roleplaycore.AziendaDepartment.AziendaAdmin.Events.onInventoryClick(Events.java:404) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: dev.mattytomas.anvilgui.version.Wrapper1_16_R3
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at dev.mattytomas.anvilgui.version.VersionMatcher.match(VersionMatcher.java:28) ~[?:?]
        at dev.mattytomas.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:39) ~[?:?]
        at dev.mattytomas.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:558) ~[?:?]
        at dev.mattytomas.roleplaycore.AziendaDepartment.AziendaAdmin.Events.depositMoney(Events.java:234) ~[?:?]
        at dev.mattytomas.roleplaycore.AziendaDepartment.AziendaAdmin.Events.onInventoryClick(Events.java:404) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        ... 18 more`

**Comment by MattyTomas** [comment]
I'm using Java 16 on the server and for the plugin compilation, everything is set up right in the pom.xml as described in the instructions.

**Comment by MattyTomas** [comment]
I have minimizejars, but also the code that you recommend to use, what's wrong?

**Comment by mastercake10** [comment]
Ensure that your filter for `<minimizeJar>` is set up right. Your version wrapper files are missing from the final jar.

**Comment by MattyTomas** [comment]
Now everything works but when compiling the jar I get this warning: my-plugin-name.jar, anvilgui-1.6.3-SNAPSHOT.jar define 1 overlapping resource: 
  - META-INF/MANIFEST.MF
