### ISSUE TITLE
Why ? AnvilGUI does not support server version "1_8_R3" ? 

### ISSUE THREAD

**Issue by DisPro** [WesJD/AnvilGUI#274]
Hello, i have a probleme 
org.bukkit.command.CommandException: Unhandled exception executing command 'tag' in plugin Senoria-Lobby valpha-1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [?:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [?:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_372]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_372]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
Caused by: java.lang.ExceptionInInitializerError
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:550) ~[?:?]
        at fr.senoriadev.dispro.lobby.commands.CommandGP.onCommand(CommandGP.java:60) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 15 more
Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_8_R3"
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:32) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:42) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:550) ~[?:?]
        at fr.senoriadev.dispro.lobby.commands.CommandGP.onCommand(CommandGP.java:60) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.Wrapper1_8_R3
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_372]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_372]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_372]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:28) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:42) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:550) ~[?:?]
        at fr.senoriadev.dispro.lobby.commands.CommandGP.onCommand(CommandGP.java:60) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 15 more

**Comment by WesJD** [comment]
Because you have not shaded the library properly into your plugin.

**Comment by DisPro** [comment]
i use shadowjar on gradle

**Comment by WesJD** [comment]
This is not a support forum for build systems.
