### ISSUE TITLE
Error when changing item displayname or setting text

### ISSUE THREAD

**Issue by AxalotLS** [WesJD/AnvilGUI#275]
When I try to change the name of an item or change the text, this error occurs.
java.lang.NullPointerException: Cannot invoke "String.length()" because "input" is null
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:207) ~[adventure-text-serializer-legacy-4.14.0.jar:?]
        at net.minecraft.world.inventory.AnvilMenu.createResult(AnvilMenu.java:342) ~[?:?]
        at net.wesjd.anvilgui.version.Wrapper1_20_R1$AnvilContainer.m(Wrapper1_20_R1.java:96) ~[BermudaGuilds-0.1.jar:?]
        at net.minecraft.world.inventory.ItemCombinerMenu.slotsChanged(ItemCombinerMenu.java:112) ~[?:?]
        at net.minecraft.world.inventory.ItemCombinerMenu$3.setChanged(ItemCombinerMenu.java:103) ~[?:?]
        at net.minecraft.world.SimpleContainer.setItem(SimpleContainer.java:207) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftResultInventory.setItem(CraftResultInventory.java:37) ~[purpur-1.20.jar:git-Purpur-1990]
        at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:170) ~[BermudaGuilds-0.1.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.access$1000(AnvilGUI.java:37) ~[BermudaGuilds-0.1.jar:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:561) ~[BermudaGuilds-0.1.jar:?]
        at com.axalotl.bermudaguilds.inventories.GuildInventory.guildDescriptionInput(GuildInventory.java:288) ~[BermudaGuilds-0.1.jar:?]

**Comment by WesJD** [comment]
Please provide a minimally reproducible example of the problem so we can better understand!

**Comment by AxalotLS** [comment]
If you use the .text() function with any text, this error occurs.
Code:
public void guildDescriptionInput(Player player) {
        ItemStack leftItem = new ItemStack(Material.PAPER);
        ItemMeta left_item_meta = leftItem.getItemMeta();
        String text;
        if (this.manager.findGuild(player.getUniqueId()).isPresent()) {
            Guild g = this.manager.findGuild(player.getUniqueId()).get();
            text = g.getDescription() != null ? g.getDescription() : "Description";
        } else text = "Description";
        List<String> list = new ArrayList<>();
        list.add(Colorize.format("&fGuild description."));
        Objects.requireNonNull(left_item_meta).setLore(list);
        leftItem.setItemMeta(left_item_meta);
        new AnvilGUI.Builder()
                .onClickAsync((slot, stateSnapshot) -> CompletableFuture.supplyAsync(() -> {
                    if (slot != AnvilGUI.Slot.OUTPUT) {
                        return Collections.emptyList();
                    }
                    if (stateSnapshot.getOutputItem() == null) {
                        return Collections.emptyList();
                    }
                    if (stateSnapshot.getText() == null) {
                        return Collections.emptyList();
                    } else {
                        this.manager.findGuild(player.getUniqueId()).ifPresent(guild -> guild.setDescription(stateSnapshot.getText()));
                        ChestGui gui = createGuildGui(player);
                        return Arrays.asList(
                                AnvilGUI.ResponseAction.close(),
                                AnvilGUI.ResponseAction.run(() -> gui.show(player))
                        );
                    }
                }))
                .text("Test")
                .itemLeft(leftItem)
                .title("Guild Description")
                .plugin(plugin)
                .open(player);
    }

**Comment by Sytm** [comment]
Please update your Purpur build to 1993 or later you are testing the plugin on. On of my users also had a similar problem and I stumbled upon this issue on their repo: https://github.com/PurpurMC/Purpur/issues/1344

**Comment by AxalotLS** [comment]
thanks it worked
