### ISSUE TITLE
AnvilGUI does not support server version "1_20_R1"

### ISSUE THREAD

**Issue by misteeka** [WesJD/AnvilGUI#276]
Doesn't work on 1.20 server (I use 1.6.5-SNAPSHOT)

`
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: AnvilGUI does not support server version "1_20_R1" [in thread "Server thread"]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:32)
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:42)
        ... 29 more
`

**Comment by Sytm** [comment]
Then use `1.6.6.-SNAPSHOT` instead
