### ISSUE TITLE
Error how to fix

### ISSUE THREAD

**Issue by TheRedEnd2000** [WesJD/AnvilGUI#280]
Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder
	at de.theredend2000.duels.inventorys.kitMenus.KitListMenu.handleMenu(KitListMenu.java:80) ~[?:?]
	at de.theredend2000.duels.listeners.InventoryClickListener.onClickInventory(InventoryClickListener.java:41) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder
	at de.theredend2000.duels.inventorys.kitMenus.KitListMenu.handleMenu(KitListMenu.java:80) ~[?:?]
	at de.theredend2000.duels.listeners.InventoryClickListener.onClickInventory(InventoryClickListener.java:41) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 20 more
	
	hey guys, so every time i tried to use it this error is popping up how can i fix it i added everythink in my pom.xml
	
	can someone help me please

**Comment by Sytm** [comment]
It looks like you didn't properly shade AnvilGUI at all. See https://github.com/WesJD/AnvilGUI#as-a-dependency

**Comment by TheRedEnd2000** [comment]
i have added it into my pom.xml but i didnt worked
