### ISSUE TITLE
Error when trying using AnvilGUI on spigot 1.20.1 

### ISSUE THREAD

**Issue by Mapty231** [WesJD/AnvilGUI#285]
As the title states.
I put this code in an event:
`
VersionMatcher versionMatcher = new VersionMatcher();
System.out.println(versionMatcher.match());
`
And whenever the event triggers i get this error:
`[17:16:21] [Server thread/ERROR]: Could not pass event InventoryClickEvent to FileManager v0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2782) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/version/VersionMatcher
	at me.tye.filemanager.commands.fileCommand.FileGui.edit(FileGui.java:246) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 20 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.VersionMatcher
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.tye.filemanager.commands.fileCommand.FileGui.edit(FileGui.java:246) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 20 more`

**Comment by Sytm** [comment]
It looks like you didn't shade / shadow AnvilGUI properly.
Also, why are you accessing the VersionMatcher? Everything you need to interact with is inside the AnvilGUI class and its subclasses

<details>
<summary>Properly formatted stacktrace</summary>

```
[17:16:21] [Server thread/ERROR]: Could not pass event InventoryClickEvent to FileManager v0.1 org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] 
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] 
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] 
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] 
    at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2782) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1151) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1123) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1018) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3864-Spigot-d2eba2c-00f5a80] 
    at java.lang.Thread.run(Thread.java:833) ~[?:?] 
 Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/version/VersionMatcher 
    at me.tye.filemanager.commands.fileCommand.FileGui.edit(FileGui.java:246) ~[?:?] 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] ... 20 more 
 Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.VersionMatcher 
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] 
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] 
    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 
    at me.tye.filemanager.commands.fileCommand.FileGui.edit(FileGui.java:246) ~[?:?] 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?] ... 20 more
```
</details>

**Comment by Mapty231** [comment]
i copied the repository and dependency from the README file if that's what you mean by shading. I'm not very familiar with maven. Do you know where i could find a guide on how to shade / shadow with maven?
And i used the version matcher as i was getting errors.

**Comment by joestr** [comment]
Shading AnvilGUI correctly is just a paragraph below in the Readme file.
