### ISSUE TITLE
1.14.4 Looks like NMS Mappings changed

### ISSUE THREAD

**Issue by wispoffates** [WesJD/AnvilGUI#42]
[23:06:43] [Server thread/WARN]: [ArtMap] Task #152 for ArtMap v3.3.1 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.ContainerProperty.a(I)V
        at net.wesjd.anvilgui.version.Wrapper1_14_R1$AnvilContainer.e(Wrapper1_14_R1.java:132) ~[?:?]
        at net.minecraft.server.v1_14_R1.ContainerAnvil.a(ContainerAnvil.java:123) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.ContainerAnvil$1.update(ContainerAnvil.java:42) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:158) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftResultInventory.setItem(CraftResultInventory.java:37) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:149) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:128) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:94) ~[?:?]
        at me.Fupery.ArtMap.Painting.ArtistHandler.lambda$handlePacket$2(ArtistHandler.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-8b09d98]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by WesJD** [comment]
Not sure what Mojang is doing these days... the revision number should have increased.

**Comment by wispoffates** [comment]
Not sure if this helps in this case but I've used it to some success in 1.13 when they decided to changes Maps IDs from short to int and back.

"The only guarantee given about NMS is that CraftMagicNumbers.getMappingsVersion() will be changed if any mappings changes are made (which could be frequently)."

**Comment by WesJD** [comment]
Thanks for the tip. Might have to use that at this point.

**Comment by kiranhart** [comment]
Hey, I recently started using this API, and ran into this same issue, is there any update on a fix for this?

**Comment by WesJD** [comment]
Not yet. If you'd like to help out, feel fee to submit a PR. Otherwise, the maintainer or I will get to it eventually.

**Comment by tchristofferson** [comment]
I will commit a change to fix this today at some point.

**Comment by wispoffates** [comment]
I think the api pom.xml is missing the include from 1_14_4_R1.

[01:08:19] [Server thread/WARN]: [ArtMap] Task #138 for ArtMap v3.3.4 generated an exception
java.lang.NoClassDefFoundError: net/wesjd/version/special/AnvilContainer1_14_4_R1
        at net.wesjd.anvilgui.version.Wrapper1_14_R1.newContainerAnvil(Wrapper1_14_R1.java:105) ~[?:?]
