### ISSUE TITLE
"You can't close an inventory that isn't open!"

### ISSUE THREAD

**Issue by einTosti** [WesJD/AnvilGUI#58]
This error occurs if a player closes the inventory before the code (before the GUI returns close) has fully run

`org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: You can't close an inventory that isn't open!
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	at net.wesjd.anvilgui.AnvilGUI.closeInventory(AnvilGUI.java:165) ~[?:?]
	at net.wesjd.anvilgui.AnvilGUI$ListenUp.onInventoryClick(AnvilGUI.java:208) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.jar:git-Spigot-f39a89e-73698cf]
	... 17 more
`

**Comment by tchristofferson** [comment]
Are you trying to do this asynchronously?

**Comment by einTosti** [comment]
Nope

**Comment by tchristofferson** [comment]
Can you paste the code you used to create the Builder and specify how to replicate the issue?

**Comment by einTosti** [comment]
Builder:
`public void openWorldAnvil(Player p, WorldType worldType, String template) {
        new AnvilGUI.Builder()
                .onComplete((player, text) -> {
                    String worldName = text.trim().replace(" ", "_").replaceAll("[^A-Za-z0-9/_-]", "");
                    if (worldType == WorldType.TEMPLATE) {
                        createTemplateWorld(player, worldName, ChatColor.stripColor(template));
                    } else {
                        createWorld(player, worldName, worldType);
                    }
                    return AnvilGUI.Response.close();
                })
                .text(plugin.getString("worlds_world_name"))
                .plugin(plugin)
                .open(p);
    }`

Create world and create template both generate a world, which just takes some time, what I think is the problem:
`private org.bukkit.World generateWorld(World world) {
        WorldCreator worldCreator = new WorldCreator(world.getName());

        org.bukkit.WorldType worldType;
        switch (world.getType()) {
            case VOID:
                worldCreator.generateStructures(false);
                worldType = org.bukkit.WorldType.FLAT;
                if (XMaterial.isNewVersion()) {
                    worldCreator.generator(new ChunkGenerator() {
                        @Override
                        public ChunkData generateChunkData(org.bukkit.World world, Random random, int x, int z, BiomeGrid biome) {
                            return createChunkData(world);
                        }
                    });
                } else {
                    worldCreator.generatorSettings("2;0;1");
                }
                break;
            case FLAT:
            case PRIVATE:
                worldCreator.generateStructures(false);
                worldType = org.bukkit.WorldType.FLAT;
                break;
            default:
                worldCreator.generateStructures(true);
                worldType = org.bukkit.WorldType.NORMAL;
                break;
        }
        worldCreator.type(worldType);

        org.bukkit.World bukkitWorld = Bukkit.createWorld(worldCreator);

        bukkitWorld.setDifficulty(Difficulty.PEACEFUL);
        bukkitWorld.setTime(6000);
        bukkitWorld.setGameRuleValue("doDaylightCycle", "false");
        bukkitWorld.setGameRuleValue("doMobSpawning", "false");
        bukkitWorld.setGameRuleValue("doFireTick", "false");

        switch (world.getType()) {
            case VOID:
                bukkitWorld.getBlockAt(0, 64, 0).setType(Material.GOLD_BLOCK);
                bukkitWorld.setSpawnLocation(0, 65, 0);
                break;
            case FLAT:
            case PRIVATE:
                bukkitWorld.setSpawnLocation(0, 4, 0);
                break;
        }
        return bukkitWorld;
    }`

**Comment by tchristofferson** [comment]
I can't replicate this. It is most likely your code causing the problem. @WesJD can probably close this issue.

**Comment by einTosti** [comment]
It's probably because my PC isn't the best anymore. Everytime when I create a world and leave the GUI when the world is being created (before it finishes) the error occurs.

Would this be a solution?
https://github.com/WesJD/AnvilGUI/issues/34
