### ISSUE TITLE
Not working on 1.15.2?

### ISSUE THREAD

**Issue by 7rory768** [WesJD/AnvilGUI#78]
`[23:41:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to RPGHorses v1.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2148) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ExceptionInInitializerError
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:319) ~[?:?]
        at org.plugins.rpghorses.listeners.InventoryClickListener.onClick(InventoryClickListener.java:176) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        ... 17 more
Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
        at net.wesjd.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:47) ~[?:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_241]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:47) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:33) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:319) ~[?:?]
        at org.plugins.rpghorses.listeners.InventoryClickListener.onClick(InventoryClickListener.java:176) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-95bd423]
        ... 17 more`

It says my server version isn't supported by AnvilGUI by I am running 1.15.2 (fresh build from BuildTools)

`					AnvilGUI.Builder builder = new AnvilGUI.Builder().plugin(plugin);
					builder.onClose(player -> {
						horseOwner.openHorseGUI(horseOwner.getHorseGUI());
					}).onComplete((player, text) -> {
							String oldName = rpgHorse.getName(), name = text.split("\\s")[0];
							rpgHorse.setName(name);
							this.stableGuiManager.updateRPGHorse(rpgHorse);
							this.messagingUtil.sendMessage(p, this.plugin.getConfig().getString("messages.horse-renamed").replace("{OLD-HORSE-NAME}", oldName), rpgHorse);
							horseOwner.openHorseGUI(horseOwner.getHorseGUI());
						return AnvilGUI.Response.close();
					});
					builder.text("").open(p);`

Pom:
`        <dependency>
            <groupId>com.github.WesJD</groupId>
            <artifactId>AnvilGUI</artifactId>
            <version>master</version>
            <scope>compile</scope>
        </dependency>`

**Comment by 7rory768** [comment]
I changed the version in my pom.xml and it works fine now, thanks
