### ISSUE TITLE
NoClassDefFoundError (AnvilGUI$Builder)

### ISSUE THREAD

**Issue by ssomar1607** [WesJD/AnvilGUI#86]
Hello i have Caused by: java.lang.NoClassDefFoundError: net/wesjd/anvilgui/AnvilGUI$Builder, i have try "use mvn clean package command to build the uber jar." but it doesnt work.

**Comment by SorninL** [comment]
I have the same issue. Tested whithe mvn clean install (and clean package).

on **net.minecraft.server.v1_15_R1**

To complete the message above : 

```
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.AnvilGUI$Builder
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-201]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-201]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
... 23 more
```

Thanks for that works, and thanks for your futures answers

**Comment by portlek** [comment]
Could you show us your pom.xml and inside .jar(with rar) picture?

**Comment by SorninL** [comment]
Hi ! Thanks for replying !

Here's the link to my pom.xml -> [pom.xml
](https://hastebin.com/ewoziwuzig.xml)

And here's the inside of the jar (i'm on intellij) tell me if you need the rar one -> [image](https://i.gyazo.com/f46b0048bda770919aab19687db33f81.png)

Thanks !

**Comment by portlek** [comment]
Could you send your built jar into my email adress `utsukushihito@outlook.com`

**Comment by portlek** [comment]
never mind i found the issue
```xml
    <dependency>
        <groupId>com.github.WesJD.AnvilGUI</groupId>
        <artifactId>anvilgui</artifactId>
        <version>master-SNAPSHOT</version>
    </dependency>
```
use that dependency.

**Comment by SorninL** [comment]
So, we're able to remove the repo jitpack ?

**Comment by portlek** [comment]
> So, we're able to remove the repo jitpack ?

No, the repository case should be.
