### ISSUE TITLE
Version is not supported

### ISSUE THREAD

**Issue by TheRealJan** [WesJD/AnvilGUI#93]
Hello on the newest Spigot Version (Minecraft 1.16.1) I get the version error. 
```
[13:33:05] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Essentials v1.0-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2190) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:944) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:937) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:921) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:853) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:165) ~[server.jar:git-Spigot-758abbe-3f0c333]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ExceptionInInitializerError
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:380) ~[?:?]
        at tk.therealjan.essentials.Events.HomesGUIEvent.onHomesGUIEvent(HomesGUIEvent.java:83) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-758abbe-3f0c333]
        ... 18 more
Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
        at net.wesjd.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:49) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
        at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:49) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:380) ~[?:?]
        at tk.therealjan.essentials.Events.HomesGUIEvent.onHomesGUIEvent(HomesGUIEvent.java:83) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-758abbe-3f0c333]
        ... 18 more
```

**Comment by Butterness01** [comment]
This issue still happens to me. I tried multiple times with both
```
<dependency>
    <groupId>com.github.WesJD.AnvilGUI</groupId>
    <artifactId>anvilgui</artifactId>
    <version>master</version>
</dependency>
```
and
```
<dependency>
    <groupId>com.github.WesJD.AnvilGUI</groupId>
    <artifactId>anvilgui</artifactId>
    <version>master-SNAPSHOT</version>
</dependency>
```

**Comment by Sytm** [comment]
It works perfectly for me, probably because I deploy the built Jar into my own repository, because JitPack is just so unreliable for me that I gave up on that service. One solution I recommend for you is to:
```
// Create a temporary directory and enter it
mkdir /tmp/directory
cd /tmp/directory
// Clone the repository
git clone https://github.com/WesJD/AnvilGUI.git
// Build and install AnvilGUI locally
mvn install
```
Now you should be able to use it using the version `1.3.0`

**Comment by Butterness01** [comment]
@Sytm,
I'm not experienced with Git. When I try to build, my build fails:
```
[ERROR] No plugin found for prefix 'https' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Butterness\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

**Comment by Sytm** [comment]
@Butterness01 This is the repo I am using, put it into your maven pom of your project and you should be good to go because I can't really help you with more than what I posted here
```xml
        <repository>
            <id>sytm-nexus</id>
            <url>https://repo.sytm.de/repository/maven-hosted/</url>
        </repository>
```
